service: legendary-goggles

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: us-east-1

package:
  individually: true
  patterns:
    - '!./**'

functions:
  tvm:
    handler: src/token_vending_machine.handler
    package:
      patterns:
        - ./src/token_vending_machine.py
        - ./src/policy-template/**

resources:
  Resources:
    ${file(./resources/role.yaml)}
    ${file(./resources/dynamodb.yaml)}

plugins:
  - serverless-python-requirements