service: legendary-goggles

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: us-east-1

package:
  individually: true
  patterns:
    - '!./**'

functions:
  tvm:
    handler: token_vending_machine.handler
    package:
      patterns:
        - token_vending_machine.py

resources:
  Resources:
    ${file(./resources/dynamodb.yaml)}