LegendaryGogglesTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: legendaryGoggles
    AttributeDefinitions:
      - AttributeName: pk
        AttributeType: S
    KeySchema:
      - AttributeName: pk
        KeyType: HASH
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1